spring:
  profiles:
    active: dev

---
Spring:
  profiles: dev     # 开发环境配置
  devtools:
    livereload:
      port: 35730

server:
  port: 8080
  servlet:
    context-path: /

directory:
  root: C:\Users\Administrator\Desktop\public
